# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e06c421c6e187b921071cdfd576c17ac2bfaf5c577806de4a5a1e36c1d27214a1150183530beb1ea077d3cbc098a4863873343979b384c6d70c508295981ec

test:
  secret_key_base: c133c10130b5f628fd241e6ae69d843a4746efeeda91112571986592ddf3dfa475455b6b89e73d5f9b2f8e79e27adebf814e1b79b02e487695897792eda6c17d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
